repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-merge-conflict
          - id: check-ast
          - id: debug-statements
          - id: check-toml
          - id: check-json
          - id: check-xml
          - id: name-tests-test
            args: ["--pytest-test-first"]
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            additional_dependencies: [Flake8-pyproject]
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
    - repo: https://github.com/pycqa/autoflake
      rev: v2.1.1
      hooks:
          - id: autoflake
            args:
                [
                    "--in-place",
                    "--expand-star-imports",
                    "--remove-all-unused-imports",
                    "--remove-unused-variables",
                    "--ignore-init-module-imports",
                ]
